### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by BWindey** [MCMrARM/mc-android-version-switcher#2]
This app got me excited, I would love to play on beta versions, or explore the really old versions, but it does not work for me.
I downloaded the app via mediafire (the .apk file). The menu comes up when I open, all no problem. When I select a version to install, it downloads it and displays "downloaded", and when I press it again it asks to remove Minecraft. I do that, but then it just closes the version switcher, and nothing happens. When I reopen the app the version I chose is again "not downloaded", when I press it it downloads, press it again it closes the app and nothing else happens. The settings for the app look all good, it has permission to download aps.
I hope this will get sorted, as I love the idea of switching between versions, and especially in this simple (looking) way.

**Comment by Kee7702** [comment]
If you close the app and it says 'Not Downloaded' on a previously installed version, that means that there was an issue retrieving the APK from Google Play API. This is most likely caused by the lack of authentication, or the authenticated google account didn't purchase MC. Make sure you sign in with the correct google account and try again. If it still doesn't work, try a slightly newer MC version. Some older version codes do not work, and I've noticed this personally but I am currently working on that issue privately and may reach out to MCMrARM when I have a full version list compiled.

**Comment by Kee7702** [comment]
If you've tried everything listed and it still does not work, know that this app is less stable and less functional on some devices and you may just be unlucky.
